import {
  Rocket, Database, Radio, FileText, Users, Stethoscope, Shield, Lightbulb,
  Keyboard, HelpCircle, MapPin, Siren, Car, Clock, AlertTriangle, Settings,
  MessageSquare, CheckCircle2, Zap
} from "lucide-react";

export const HELP_CATEGORIES = [
  {
    id: "getting-started",
    title: "Getting Started",
    icon: Rocket,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    articles: [
      {
        id: "overview",
        title: "System Overview",
        summary: "Understand the two main modules and how they connect.",
        tags: ["basics", "introduction"],
        steps: [
          "OCRP Hub has two core modules: the Roster System and the CAD System.",
          "The Roster System manages departments, members, shifts, LOA requests, vehicles, uniforms, and documents.",
          "The CAD System is the Computer-Aided Dispatch suite with department-specific dashboards for Police, Fire, EMS, Dispatch, and Civilians.",
          "Both modules share department data — set up departments once and they appear in both systems.",
          "Use the Home page to switch between modules at any time.",
        ],
      },
      {
        id: "discord-link",
        title: "Linking Your Discord Account",
        summary: "Verify your Discord identity to unlock CAD access.",
        tags: ["discord", "verification", "setup"],
        steps: [
          "Navigate to Settings → Discord Linking (or CAD Settings → Account).",
          "Choose your verification method: Bot DM or Discord OAuth.",
          "Bot DM: Enter your Discord ID, then a verification code is sent to your Discord DMs. Enter the code to confirm.",
          "OAuth: Click 'Connect with Discord' to authorize via Discord's secure login — no code needed.",
          "Once linked, your Discord roles are synced to determine your departments and supervisor status.",
          "If you change roles in Discord, log out and back in to re-sync permissions.",
        ],
      },
      {
        id: "themes",
        title: "Customizing Your Theme",
        summary: "Switch between Modern Dark and Retro Terminal themes.",
        tags: ["theme", "appearance", "customization"],
        steps: [
          "Open CAD Settings from the sidebar or Settings page.",
          "Choose between 'Modern Dark' (sleek, glassmorphic) and 'Retro Terminal' (CRT scanlines, monospace, ASCII frames).",
          "The Retro theme features a command-line navigation bar and terminal-style panels.",
          "Theme selection persists across sessions on your device.",
          "Community admins can set a global accent color in the Admin Panel → Community Info.",
        ],
      },
    ],
  },
  {
    id: "cad-system",
    title: "CAD System",
    icon: Radio,
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    articles: [
      {
        id: "departments",
        title: "Selecting & Entering a Department",
        summary: "Choose your department dashboard.",
        tags: ["departments", "navigation"],
        steps: [
          "From the CAD landing page (/cad), you'll see all available departments as cards.",
          "Each card shows the department name, category (Police, Fire, EMS, etc.), and member count.",
          "Click a department card to enter that department's dashboard.",
          "Police departments open the MDT, Fire/EMS open their respective boards, and Civilian departments open the Civilian CAD.",
          "Dispatch has its own dedicated dispatch interface accessible from the sidebar.",
        ],
      },
      {
        id: "clock-in",
        title: "Clocking In & Out",
        summary: "Start and end your duty shifts.",
        tags: ["shift", "clock", "duty"],
        steps: [
          "When you enter a department dashboard, you'll see a Clock-In screen if you're not on duty.",
          "Select your callsign and rank, then click 'Clock In' to start your shift.",
          "Your session is now active — other units can see your status on the dispatch board.",
          "To end your shift, use the status controls to go 'Off Duty' or click the logout/clock-out button in the taskbar.",
          "Shift durations are automatically tracked and appear in the Roster → Shifts page.",
        ],
      },
      {
        id: "status",
        title: "Managing Your Unit Status",
        summary: "Available, Busy, On Call, Unavailable, and Panic.",
        tags: ["status", "dispatch", "units"],
        steps: [
          "Use the status buttons in the taskbar (bottom of screen) or keyboard shortcuts to change status.",
          "Available (1): Ready for assignment, shown green on dispatch.",
          "Busy (2): On a call or en route — dispatch sees you're occupied.",
          "On Call (3): Actively engaged with an active call.",
          "Unavailable (4): Out of service (break, equipment issue, etc.).",
          "Panic (P): Emergency button — triggers an alert to all units and dispatch with your location.",
          "Status changes are visible to dispatch in real-time via WebSocket subscriptions.",
        ],
      },
      {
        id: "panic",
        title: "Using the Panic Button",
        summary: "Emergency alert for officer-down situations.",
        tags: ["panic", "emergency", "safety"],
        steps: [
          "Press 'P' on your keyboard or the panic button in the taskbar to trigger an emergency alert.",
          "All active units and dispatch receive an immediate visual and audio alert.",
          "Your unit flashes red on the dispatch map and unit list.",
          "The alert includes your callsign, name, and last known location.",
          "Press the panic button again or set your status to Available to clear the alert.",
          "Custom panic notification tones can be configured in Admin Panel → Notification Tones.",
        ],
      },
    ],
  },
  {
    id: "mdt-dispatch",
    title: "MDT & Dispatch",
    icon: Siren,
    color: "text-red-400",
    bg: "bg-red-500/10",
    articles: [
      {
        id: "dispatch-view",
        title: "Dispatch View",
        summary: "Create and manage active calls, assign units.",
        tags: ["dispatch", "calls", "assignment"],
        steps: [
          "The Dispatch view (F1) is your command center for active calls.",
          "Create a new call by clicking 'New Call' — enter call type, priority, location, and description.",
          "Active calls appear in the left panel, sorted by priority.",
          "Assign units by dragging them onto a call, or clicking 'Assign' next to a unit.",
          "Each assignment is logged with a timestamp in the call's assignment log.",
          "Close calls by changing their status to 'Closed' — all units are released.",
        ],
      },
      {
        id: "lookups",
        title: "Person, Vehicle & Address Lookups",
        summary: "Search the database for civilians, vehicles, and locations.",
        tags: ["lookup", "search", "records"],
        steps: [
          "Open the Lookups view (F2) to search across the database.",
          "Person Search: Search by name to find civilian records — shows licenses, medical info, warrants, and prior reports.",
          "Vehicle Search: Search by plate to see registration, insurance, stolen status, and owner.",
          "Address Search: Look up street names for call routing and postal codes.",
          "Results are department-scoped — you only see records relevant to your department.",
          "From any search result, you can create a linked report or add to a BOLO/warrant.",
        ],
      },
      {
        id: "records",
        title: "Records: Reports, Warrants & BOLOs",
        summary: "File and manage law enforcement records.",
        tags: ["records", "reports", "warrants", "bolo"],
        steps: [
          "Open the Records view (F3) to manage all law enforcement documentation.",
          "Reports: Choose from 13 report types (Arrest, Citation, Use of Force, MVA, Traffic Stop, etc.).",
          "Each report type has department-specific fields that auto-adapt to your department category.",
          "Police and Private Security reports include charge sections with auto-populated penal code details.",
          "Warrants: Create active warrants with charges, bail amounts, and issuance details.",
          "BOLOs: Issue Be-On-the-Lookout alerts for persons, vehicles, or firearms.",
          "All records can be linked to active calls and civilian profiles.",
        ],
      },
      {
        id: "my-call",
        title: "My Call View",
        summary: "Focus on your currently assigned call.",
        tags: ["call", "assignment", "focus"],
        steps: [
          "The My Call view (F4) shows details of the call you're currently assigned to.",
          "View call description, location, caller info, and all assigned units.",
          "Add CAD notes visible to dispatch and other assigned units.",
          "View the assignment log timeline showing who joined/left and when.",
          "The call auto-updates in real-time — no refresh needed.",
        ],
      },
      {
        id: "groups",
        title: "Unit Groups",
        summary: "Create multi-officer teams for coordinated responses.",
        tags: ["groups", "units", "teams"],
        steps: [
          "Open the Groups view (F5) to manage unit groups.",
          "Create a group with a name, minimum/maximum seat count, and department.",
          "Assign multiple units to a group for coordinated call responses.",
          "Group status reflects the collective status of its members.",
          "Supervisors can create and manage groups; regular officers can join existing ones.",
        ],
      },
    ],
  },
  {
    id: "civilian",
    title: "Civilian Suite",
    icon: Users,
    color: "text-green-400",
    bg: "bg-green-500/10",
    articles: [
      {
        id: "create-civilian",
        title: "Creating a Civilian Character",
        summary: "Build your civilian profile with full personal details.",
        tags: ["civilian", "character", "profile"],
        steps: [
          "From the Civilian Dashboard, click 'Create Character' to start a new civilian.",
          "Fill in personal details: name, DOB, gender, physical description, address, and contact info.",
          "Add medical information: allergies, medications, medical history, and food allergies.",
          "Each user can create up to 5 civilian characters (configurable by admin).",
          "Your civilians are private to you — only you and admins can see and edit them.",
          "Photo URLs can be added for visual identification.",
        ],
      },
      {
        id: "dmv",
        title: "DMV & Licenses",
        summary: "Manage driver, weapon, pilot, and hunting licenses.",
        tags: ["dmv", "licenses", "driving"],
        steps: [
          "Open the Civilian DMV from the dashboard to manage licenses for your characters.",
          "Driver's License: Apply for types and endorsements (CDL, Motorcycle, etc.).",
          "Weapon License: Register firearm permits with specific type categories.",
          "Pilot License: Get rank-based endorsements for different aircraft classes.",
          "DCNR / Fish & Game: Multi-select license types with hunting stamps.",
          "License statuses: Valid, Suspended, Revoked, or None.",
          "Police officers can view (read-only) and suspend licenses during traffic stops.",
        ],
      },
      {
        id: "vehicles",
        title: "Registering Vehicles",
        summary: "Create and manage civilian vehicle records.",
        tags: ["vehicle", "registration", "civilian"],
        steps: [
          "From the Civilian Dashboard, navigate to 'My Vehicles'.",
          "Create a vehicle with plate, make, model, color, year, and type.",
          "Track registration status (Valid, Expired, Suspended, None) and insurance status.",
          "Mark vehicles as stolen — this flags them in police lookups immediately.",
          "Officers searching by plate will see all vehicle details and owner information.",
        ],
      },
      {
        id: "firearms",
        title: "Registering Firearms",
        summary: "Create firearm records linked to your civilians.",
        tags: ["firearm", "registration", "weapon"],
        steps: [
          "From the Civilian Dashboard, navigate to 'My Firearms'.",
          "Register a firearm with serial number, model, caliber, and manufacturer.",
          "Track registration status and stolen flags.",
          "Stolen firearms appear in police lookups and BOLOs.",
          "Link firearms to your weapon license for verification.",
        ],
      },
    ],
  },
  {
    id: "ems-fire",
    title: "EMS & Fire",
    icon: Stethoscope,
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    articles: [
      {
        id: "pcr",
        title: "Patient Care Reports (PCR)",
        summary: "Comprehensive medical documentation with tabbed workflow.",
        tags: ["pcr", "ems", "medical", "report"],
        steps: [
          "Create a PCR from the EMS dashboard or by linking a civilian from lookups.",
          "Patient Tab: Auto-populates from civilian records — verify and edit as needed.",
          "Assessment Tab: Document LOC (AVPU), GCS, pupils, skin, airway, breathing, and circulation.",
          "Vitals Tab: Add timed vital sign entries (BP, HR, RR, SpO2, temp, BGL, pain).",
          "Treatment Tab: Log interventions, IV access, and medications administered with routes.",
          "Narrative Tab (final): Write your PCR narrative or use AI to auto-generate from entered data.",
          "AI Narrative: Click 'Generate Narrative' to compile all tab data into a professional SOAP-format narrative.",
          "Set disposition (Transported, Treated/Released, Refused AMA, etc.) and destination.",
        ],
      },
      {
        id: "fire-board",
        title: "Fire Dashboard",
        summary: "Incident response and fire-specific reports.",
        tags: ["fire", "dashboard", "incident"],
        steps: [
          "The Fire board opens with active fire calls and available units.",
          "Fire reports include alarm times (alarm, arrival, under control, scene clear).",
          "Document fire type (Structure, Vehicle, Grass/Brush), alarm level, and cause.",
          "Track apparatus responded, personnel count, damage estimates, injuries, and fatalities.",
          "MVA/Extrication reports are available for rescue scenarios.",
        ],
      },
      {
        id: "ems-board",
        title: "EMS Dashboard",
        summary: "Medical call management and patient tracking.",
        tags: ["ems", "dashboard", "medical"],
        steps: [
          "The EMS board shows active medical calls and available ambulances/units.",
          "Create Medical reports and Use of Medications reports directly from calls.",
          "Link patients to existing civilian records for auto-populated medical history.",
          "Track transport status, destination hospital, and transport method.",
          "All EMS reports integrate with the PCR system for comprehensive documentation.",
        ],
      },
    ],
  },
  {
    id: "admin",
    title: "Admin Panel",
    icon: Shield,
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    articles: [
      {
        id: "community-setup",
        title: "Community Setup",
        summary: "Configure branding, Discord, and global settings.",
        tags: ["admin", "setup", "branding"],
        steps: [
          "Open the Admin Panel from the sidebar (requires Supervisor or above).",
          "Community Info: Set community name, logo, accent color, Discord invite, website, and timezone.",
          "Notification Tones: Upload custom audio files for dispatch, status change, and panic alerts.",
          "Discord Settings: View guild info, sync members, and map Discord roles to departments.",
          "All branding changes propagate globally across the app.",
        ],
      },
      {
        id: "personnel",
        title: "Personnel Management",
        summary: "Manage CAD personnel and permissions.",
        tags: ["admin", "personnel", "permissions"],
        steps: [
          "Registered Users tab: View all app-registered users and toggle Admin/Supervisor flags.",
          "Discord Members tab: View all Discord guild members synced from your server.",
          "Permissions tab: Assign primary and additional departments to personnel.",
          "Sync Personnel: Pulls roles from Discord and updates department assignments and supervisor flags.",
          "Supervisor and CAD Admin flags can be set manually or synced from Discord roles.",
        ],
      },
      {
        id: "penal-codes",
        title: "Penal Codes & Charge Types",
        summary: "Configure the legal framework for reports.",
        tags: ["admin", "penal", "charges", "bonds"],
        steps: [
          "Penal Codes: Create charge entries with code, title, description, fine amount, and jail time.",
          "Charge Types: Categorize charges with custom colors for visual identification.",
          "Bond Types: Define bond categories with default amounts and colors.",
          "Bulk Import: Upload a CSV to import many penal codes at once.",
          "When filing reports, officers select charges that auto-populate fine, jail time, and bond details.",
        ],
      },
      {
        id: "danger-zone",
        title: "Danger Zone",
        summary: "Wipe operational data with caution.",
        tags: ["admin", "danger", "reset", "wipe"],
        steps: [
          "The Danger Zone is restricted to platform admins only.",
          "You can wipe specific data categories: Active Calls, Reports, Civilians, Vehicles, etc.",
          "Each wipe requires explicit confirmation and is logged in the System Logs.",
          "Use with extreme caution — wiped data cannot be recovered.",
          "System Logs record all administrative actions for audit purposes.",
        ],
      },
    ],
  },
];

export const SETUP_STEPS = [
  {
    id: "community",
    title: "Configure Community Info",
    description: "Set your community name, logo, accent color, and timezone in Admin Panel → Community Info.",
    adminOnly: true,
    link: "/cad/admin",
  },
  {
    id: "departments",
    title: "Create Departments",
    description: "Add your departments (Police, Fire, EMS, Dispatch, Civilian) with Discord role mappings.",
    adminOnly: true,
    link: "/cad",
  },
  {
    id: "discord",
    title: "Set Up Discord Integration",
    description: "Configure the Discord bot token, guild ID, and map roles to departments in Discord Settings.",
    adminOnly: true,
    link: "/cad/admin",
  },
  {
    id: "penal",
    title: "Import Penal Codes",
    description: "Add or bulk-import your penal codes, charge types, and bond types for report auto-population.",
    adminOnly: true,
    link: "/cad/admin",
  },
  {
    id: "link-discord",
    title: "Link Your Discord Account",
    description: "Verify your Discord identity via Bot DM or OAuth to unlock your department access.",
    adminOnly: false,
    link: "/settings",
  },
  {
    id: "keybinds",
    title: "Configure Keyboard Shortcuts",
    description: "Customize your MDT keybinds for status changes, view switching, and panic button.",
    adminOnly: false,
    link: "/keybinds",
  },
  {
    id: "theme",
    title: "Pick Your Theme",
    description: "Choose between Modern Dark and Retro Terminal in CAD Settings.",
    adminOnly: false,
    link: "/cad-settings",
  },
];

export const TIPS_AND_TRICKS = [
  {
    id: "quick-status",
    title: "Instant Status Changes",
    description: "Press number keys 1-4 while in the MDT to instantly change your unit status without clicking.",
    icon: Zap,
    category: "Efficiency",
  },
  {
    id: "panic-shortcut",
    title: "One-Key Panic",
    description: "Press 'P' anywhere in the MDT to instantly trigger a panic alert. Make sure you remember this keybind!",
    icon: AlertTriangle,
    category: "Safety",
  },
  {
    id: "ai-narrative",
    title: "AI Report Narratives",
    description: "On PCRs and Police reports, use 'Generate Narrative' to auto-compile all entered data into a professional narrative.",
    icon: MessageSquare,
    category: "Reports",
  },
  {
    id: "linked-records",
    title: "Linked Record Workflow",
    description: "From any person or vehicle lookup, you can directly create a linked report, warrant, or BOLO without re-entering data.",
    icon: FileText,
    category: "Workflow",
  },
  {
    id: "realtime",
    title: "Real-Time Updates",
    description: "Call and unit status updates appear instantly for all users — no need to refresh. The system uses live WebSocket subscriptions.",
    icon: Radio,
    category: "Dispatch",
  },
  {
    id: "auto-populate",
    title: "Auto-Populated Fields",
    description: "Report templates auto-fill unit number, name, rank, and agency details based on your active session — no manual entry needed.",
    icon: CheckCircle2,
    category: "Efficiency",
  },
  {
    id: "charge-autofill",
    title: "Charge Auto-Fill",
    description: "When selecting charges in a report, the fine amount, jail time, and bond type auto-populate from your penal code database.",
    icon: FileText,
    category: "Reports",
  },
  {
    id: "retro-nav",
    title: "Retro Theme Navigation",
    description: "In Retro Terminal theme, use the command-line nav bar at the top. Type or click commands to navigate — it's keyboard-first by design.",
    icon: Keyboard,
    category: "Theme",
  },
  {
    id: "civilian-limit",
    title: "Civilian Character Limits",
    description: "Each user gets 5 civilian character slots by default. Admins can adjust this limit in Community Settings.",
    icon: Users,
    category: "Civilian",
  },
  {
    id: "map-coords",
    title: "GTA V Coordinate Map",
    description: "The dispatch map uses GTA V in-game coordinates, not real-world GPS. Unit positions reflect in-game locations.",
    icon: MapPin,
    category: "Dispatch",
  },
  {
    id: "stale-data",
    title: "Clear Stale Call Data",
    description: "If your My Call tab shows outdated data, use the Records panel's 'Clear/Reset' button to refresh the UI state.",
    icon: AlertTriangle,
    category: "Troubleshooting",
  },
  {
    id: "resync",
    title: "Re-Sync After Role Changes",
    description: "If your Discord roles change, log out and back in to trigger a permission re-sync. Your department access updates automatically.",
    icon: Clock,
    category: "Troubleshooting",
  },
];

export const KEYBOARD_SHORTCUTS = [
  { action: "Switch to Dispatch View", keys: "F1", description: "Open the active calls and dispatch board." },
  { action: "Switch to Lookups View", keys: "F2", description: "Open person, vehicle, and address search." },
  { action: "Switch to Records View", keys: "F3", description: "Open reports, warrants, and BOLOs." },
  { action: "Switch to My Call View", keys: "F4", description: "View your currently assigned call details." },
  { action: "Switch to Groups View", keys: "F5", description: "Manage unit groups and teams." },
  { action: "Set Status: Available", keys: "1", description: "Mark yourself available for assignment." },
  { action: "Set Status: Busy", keys: "2", description: "Mark yourself busy / on a call." },
  { action: "Set Status: On Call", keys: "3", description: "Mark yourself actively on a call." },
  { action: "Set Status: Unavailable", keys: "4", description: "Go out of service." },
  { action: "Panic Button", keys: "P", description: "Trigger an emergency officer-down alert." },
];

export const FAQ_ITEMS = [
  {
    question: "Why can't I see my department in the CAD?",
    answer: "Your department access is determined by your Discord roles. Make sure your Discord account is linked (Settings → Discord Linking) and that you have the correct Discord role mapped to that department. If roles changed recently, log out and back in to re-sync permissions.",
  },
  {
    question: "How do I become a supervisor or CAD admin?",
    answer: "Supervisor and CAD Admin flags are assigned by platform admins in the Admin Panel → Personnel → Registered Users. Alternatively, they sync automatically from Discord supervisor roles configured per department.",
  },
  {
    question: "My status or call data seems stuck. What do I do?",
    answer: "Try the Records panel's 'Clear/Reset' button to refresh the UI state. If the issue persists, log out and back in. Real-time updates rely on WebSocket connections that may need re-establishing after long sessions.",
  },
  {
    question: "Can I customize the keyboard shortcuts?",
    answer: "Yes! Go to Keybinds (sidebar or /keybinds) to remap any shortcut. Changes are saved to your browser and persist across sessions.",
  },
  {
    question: "How does the AI narrative generation work?",
    answer: "When filing a PCR or Police report, the 'Generate Narrative' button sends all your entered data (vitals, treatments, charges, etc.) to an AI model that compiles it into a professional, formatted narrative. It's a starting point — always review and edit before filing.",
  },
  {
    question: "What's the difference between the Roster System and CAD System?",
    answer: "The Roster System is for organizational management (members, shifts, LOA, documents). The CAD System is the operational dispatch suite (MDT, calls, records, civilian database). They share department data but serve different purposes.",
  },
  {
    question: "How do I create a civilian character?",
    answer: "Go to the Civilian Dashboard, click 'Create Character', fill in the required personal details, and save. You can then manage licenses, vehicles, and firearms from the dashboard. Each user gets 5 character slots by default.",
  },
  {
    question: "Can police officers edit civilian licenses?",
    answer: "Police officers have view-only access to licenses with the ability to suspend them. Only the civilian owner or an admin can fully edit license details through the Civilian DMV.",
  },
];